spring.application.name=demo

spring.r2dbc.url=r2dbc:postgresql://localhost:5432/DATABAE_IAS
spring.r2dbc.username=ias
spring.r2dbc.password=ias

spring.sql.init.mode=never

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
